version: '2'
# 定义服务mysql,redis,php,nginx
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=database
            #- MYSQL_USER=user
            #- MYSQL_PASSWORD=password
        volumes:
            - ./mysql/var/lib/mysql:/var/lib/mysql
            - ./mysql/var/log/mysql:/var/log/mysql
            - ./mysql/run/mysqld:/var/run/mysqld
        ports:
            - "10006:3306"
    redis:
        image: daocloud.io/library/redis:5.0-rc4-alpine3.8
        expose:
            - "6379"
    php:
        depends_on:
            - mysql
            - redis
        build: ./php-fpm
        restart: always
        volumes:
            - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./www:/www
            - ./log/php-fpm/fpm-php.www.log:/var/log/fpm-php.www.log
        expose:
            - "9000"
        container_name: php
    nginx:
        depends_on:
            - php
        image: daocloud.io/library/nginx:1.11.1-alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./log/nginx:/var/log/nginx/
            - ./www:/www
        # nginx意外退出时自动重启
        restart: always

        # 映射80和443端口
        ports:
            - "80:80"
            - "443:443"
